### ISSUE TITLE
Cannot reproduce "#run CMD" step

### ISSUE THREAD

**Issue by bumengmengbu** [dustinstoltz/cartography_poetics#1]
Thanks a lot for the great paper and the CMDist package! I would like to using your word embedding technique in my own research so I am trying to reproduce your R code in this file. I've managed to reproduce the exact same figures for the first three figures. But when I try to run the fourth figure, in the "# get anchor lists and build directions" section, I cannot proceed on the "immigr.CMD <- CMDist::CMDist(dtm=news.dtm.99, 
                             cw = c("immigration", "immigration job",
                                    "immigration school", "immigration crime",
                                    "immigration family"),
                             cv = cd,
                             wv = ft.wv, 
                             scale = TRUE)" code. 

I tried several times, but each time the Rstudio tells me that there is an error like "Error in data.frame(..., check.names = FALSE) : arguments imply differing number of rows: 0, 197814". I cannot figure out what happened and could you please tell me how to fix this problem? Thank you very much!

<img width="614" alt="微信截图_20210513172803" src="https://user-images.githubusercontent.com/58286876/118148683-1a159d80-b411-11eb-9543-cb94b2555a79.png">

**Comment by bumengmengbu** [comment]
Sorry, the error hint is like this:
<img width="614" alt="微信截图_20210513172803" src="https://user-images.githubusercontent.com/58286876/118148157-99ef3800-b410-11eb-9e70-4535fa40d678.png">

**Comment by dustinstoltz** [comment]
Thanks for pointing out that error! We were able to replicate it and it turns out the DTM file had an error.  In the README, we have linked to a corrected DTM hosted on Google Drive. Please let us know if this doesn't fix the issue.

**Comment by Marshall-Soc** [comment]
Hi there! We just updated the news DTM again. The version we uploaded earlier today didn't follow the proper preprocessing steps, but the version that is up in the repo README as of now should reproduce everything correctly. If not, of course, please let us know!
